### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by themkdemiiir** [broadinstitute/str-analysis#13]
Hello, Docker isn't working. Also, I needed clarification on why you ran 'pip install' with the same requirements twice. [here](https://github.com/broadinstitute/str-analysis/blob/fd0608c666c6b63f0d0f3bc6615fbf8b7a768c6b/docker/Dockerfile#L175)

![image](https://github.com/broadinstitute/str-analysis/assets/85563797/e5081031-0f1c-4765-8466-778105d8d045)

**Comment by bw2** [comment]
To run the script inside the docker container, you should stay in the root directory (/) and just do 

```
root@da82d14a7252:/# call_non_ref_motifs

usage: call_non_ref_motifs [-h] -g {GRCh37,hg19,hg37,37,GRCh38,hg38,38} -r REFERENCE_FASTA [-o OUTPUT_PREFIX] [-s SAMPLE_ID] [--strling-genotype-table STRLING_GENOTYPE_TABLE | --run-strling] [--strling-path STRLING_PATH]
                           [--strling-reference-index STRLING_REFERENCE_INDEX] [--expansion-hunter-denovo-profile EXPANSION_HUNTER_DENOVO_PROFILE | --run-expansion-hunter-denovo] [--expansion-hunter-denovo-path EXPANSION_HUNTER_DENOVO_PATH]
                           [--run-expansion-hunter] [--expansion-hunter-path EXPANSION_HUNTER_PATH] [--use-offtarget-regions] [--run-reviewer | --run-reviewer-for-pathogenic-calls] (--variant-catalog VARIANT_CATALOG | --known-loci) [-l LOCUS]
                           [--output-format {TSV,JSON}] [-v]
                           bam_or_cram_path
```

**Comment by themkdemiiir** [comment]
Thanks, my bad. I would greatly appreciate it if you could provide me with a comprehensive usage document. You can close this issue if you wish

**Comment by bw2** [comment]
Not a problem. There's more detailed info in an older version of the README
https://github.com/broadinstitute/str-analysis/blob/8404bb65c1c3959b0d2fc3b946fe4209540fa9fc/README.md
I will need to update and make these docs easily accessible again.
Also, there's some relevant discussion in 
https://bw2.github.io/2022-01-21-STRs.html
