### ISSUE TITLE
EH-denovo bug

### ISSUE THREAD

**Issue by themkdemiiir** [broadinstitute/str-analysis#14]
Hello,

I ran these commands to test the script. 
`
call_non_ref_motifs  -r /datas/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna -g 38 --known-loci -v /datas/HG002.GRCh38.2x250.bam --output-format JSON -o /datas/HG002 --run-expansion-hunter --strling-genotype-table HG002.GRCh38.2x250.strling-genotype.txt --run-expansion-hunter-denovo
`

However, I got the following error. What can ı do in that situation?
![image](https://github.com/broadinstitute/str-analysis/assets/85563797/9c5690ae-3ed9-4ced-b0b3-0d353475f79e)

**Comment by bw2** [comment]
I am not able to reproduce the error using ExpansionHunterDenovo v0.9.1
The str_profile.json file should contain a "Depth" key/value:
```
$  cat sample.expansion_hunter_denovo.str_profile.json
{
    "Depth": 0.0008295895127478546,
    "ReadLength": 150
}

```
