### ISSUE TITLE
Discrepancy in Known Loci JSON Reference and Pathogenic Repeat Units Compared to gnomAD Website

### ISSUE THREAD

**Issue by themkdemiiir** [broadinstitute/str-analysis#15]
Hi,

I've been utilizing the known loci JSON file provided in the repository and noticed a discrepancy between the information it contains and what is presented on the gnomAD website, specifically regarding the classification of repeat units as reference or pathogenic.

For example, in the known loci JSON, the EIF4A3 gene is described as follows:
```json
"EIF4A3": {
  "LocusCoords_1based": {
    "38": "chr17:80147059-80147139",
    "37": "17:78120858-78120938"
  },
  "Motifs": {
    "REFERENCE": "CCTCGCTGTGCCGCTGCCGA, "
    "BENIGN": ["CCTCGCTGTGCCGCTGCCGA"],
    "PATHOGENIC": ["CCTCGCTGCGCCGCTGCCGA"]
  },
  "UseOfftargetRegions": false
}
```

However, on the gnomAD website, the reference repeat unit CCTCGCTGTGCCGCTGCCGA for the EIF4A3 gene (Gene region: 5'-UTR, Reference region: [17-80147059-80147139]) is classified as pathogenic.

[Gene EIF4A3 - gnomAD](https://gnomad.broadinstitute.org/gene/ENSG00000141543?dataset=gnomad_r4)
[Reference region 17-80147059-80147139 - gnomAD](https://gnomad.broadinstitute.org/region/17-80147059-80147139?dataset=gnomad_r4)

Could you please explain how the known loci JSON is created and why there could be discrepancies in the classification of repeat units compared to the gnomAD database? Understanding the process of generating the known loci JSON and the source of these differences will significantly aid my research.

**Comment by bw2** [comment]
When generating the original gnomAD callset, I wasn't aware that EIF4A3 repeats could have different motifs, and so assumed the reference motif was pathogenic and genotype it directly using ExpansionHunter and the catalog defined here:
https://github.com/broadinstitute/str-analysis/blob/main/str_analysis/variant_catalogs/variant_catalog_without_offtargets.GRCh38.json#L629-L649
The genotypes you see in gnomAD are based on the catalog definition above.

Recently, Andreas added EIF4A3 to STRipy (https://stripy.org/database/EIF4A3) along with notes from the literature which led me to also add this new definition to the known loci JSON for use with the call_non_ref_motifs script. 

One note of caution is that the STRipy locus definition also uses different start/end coordinates for the locus. You can see a more detailed comparison between the gnomad variant catalog and STRipy locus definitions @ 
https://github.com/broadinstitute/str-analysis/blob/main/str_analysis/variant_catalogs/scripts/gnomAD_STRipy_comparison.txt#L130-L133

In general the variant catalog and known loci JSON are created/updated based on what I learn from various sources as time goes by. 
I set start/end boundaries based on what I've found produces the highest genotype qualities when running ExpansionHunter. For this, I compared genotype quality between different locus definitions (eg. start / end coordinates) by running a mendelian violations analysis on internal datasets with several hundred WGS trios. 
Other resources such as STRipy may set locus boundaries based on other criteria, such as biological meaning (ie. delineating a polyglutamine stretch), or historical definitions in the literature.
