### ISSUE TITLE
TRGT vcf, multi repeat motifs in the same allele

### ISSUE THREAD

**Issue by MKaandemir** [broadinstitute/str-analysis#17]
Hi,

a TRGT VCF line contains multiple repeat motifs within the same allele, as shown below:

```
chr3    183712187    .    CTTTTATTTTATTTTATTTTATTTTATTTTATTTTA    CTTTTATTTTATTTTATTTTATTTTATTTTATTTTATTTTATTTTATTTTATTTTATGTTATTTTATGTTATTTTATTTTATGTTATTTTATGTTATTTTATGTTATTTTATGTTATGTTATGTTATGTTATGTTATGTTATGTTATGTTGTTATGTTATGTTATGTTATGTTATGTTATGTTATGTTATGTTATTTTA    0    .    TRID=YEATS2;END=183712222;MOTIFS=TTTCA,TTTTA,TGTTA,TTTTT;STRUC=<YEATS2>    GT:AL:ALLR:SD:MC:MS:AP:AM    0/1:35,193:34-36,187-196:21,16:0_7_0_0,0_16_23_0:1(0-35),1(0-80)_2(80-193):1.000000,0.958974:.,.
```
I have a few questions regarding this:

- How should we annotate such multi-motif tandem repeats in gnomAD?
- Is this a known biological phenomenon, and if so, are there specific references or examples we can look into?
- What is the recommended approach to evaluate the functional impact of such complex repeat structures?

Thank you!

Best regards,
Mehmet Kaan

**Comment by bw2** [comment]
Hi @MKaandemir 
* How should we annotate such multi-motif tandem repeats in gnomAD?
I'm not sure I understand his question. As you know, gnomAD contains only short read data and we did not run TRGT on gnomAD. 
* Is this a known biological phenomenon, and if so, are there specific references or examples we can look into?
yes, there are at least 10 disease-associated loci that are known to have this type of motif variability (including the YEATS2 locus). Others I'm aware of are described in https://github.com/broadinstitute/str-analysis/blob/main/str_analysis/data/non_ref_motif.locus_info.json 
You can also see this discussed in the literature - starting with the TRGT paper figure 4 @ https://www.nature.com/articles/s41587-023-02057-3
but also the STRipy paper under replaced / nested repeats   @ https://onlinelibrary.wiley.com/doi/10.1002/humu.24382  
as well as VAMOS  @ https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-03010-y
* What is the recommended approach to evaluate the functional impact of such complex repeat structures?
I'm not sure. If you find answers to this, I would be interested to learn them as well.

**Comment by MKaandemir** [comment]
Thanks for the help! I really appreciate it. Is Gnomad thinking about integrating long-read data?

**Comment by bw2** [comment]
Unfortunately no, I don't think there are plans right now.
